### ISSUE TITLE
Function with argument `arguments` throw error

### ISSUE THREAD

**Issue by lbelzile** [paulnorthrop/rust#4]
I have a function in `longevity` with an argument named `arguments` (a list), and this throws an error with `rust::ru`. The traceback shows the following.

```{r}
Error in eval(expr, p) : object 'theta' not found
> traceback()
8: eval(expr, p)
7: eval(expr, p)
6: eval.parent(xex)
5: to_list(deparse(call[names(call) != "arguments"]))
4: check_arguments(func = lpost_elife, call = call, arguments = arguments)
3: logf(theta, ...)
2: logf_rho(init_psi, ...)
```

Perhaps mentioning in the documentation that `call` and `arguments` are reserved and cannot be used in `lpost`?

**Comment by paulnorthrop** [comment]
No problem. Please could you provide a reproducible example, so that I can work out what is the cause of the problem? I looked in `longevity` and I couldn't find a call to `rust::ru`.

**Comment by lbelzile** [comment]
``` r
# MWE
library(longevity)
library(ggplot2)
data(japanese2, package = "longevity")
japanese2 <- japanese2[japanese2$count > 0, ]
# Define arguments that are recycled
japanese2$rtrunc <- 2020 - 
  as.integer(substr(japanese2$bcohort, 1, 4))
args <- with(japanese2, 
             list(
               time = age,
               time2 = age + 1L,
               type = "interval2",
               rtrunc = rtrunc,
               weights = count)
)
# This doesn't work...
post_samp <- rust::ru(
  logf = lpost_elife,
  arguments = args,
  family = "gp",
  trans = "BC",
  n = 1000,
  d = 2, 
  init = c(1.67, -0.08),
  lower = c(0, -1))
#> Error in eval(expr, p): object 'theta' not found

# Naming all arguments works...
post_samp <- rust::ru(
  logf = lpost_elife,
  weights = args$weights,
  rtrunc = args$rtrunc, 
  event= 3, 
  type = "interval2",
  time = args$time,
  time2 = args$time2,
  thresh = threshold,
  family = "gp",
  trans = "BC",
  n = 1000,
  d = 2, 
  init = c(1.67, -0.08),
  lower = c(0, -1))
#> Error in eval(expr, envir, enclos): object 'threshold' not found
```

<sup>Created on 2023-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by paulnorthrop** [comment]
I don't think that the issue is with passing functions arguments stored in a list called `arguments` or indeed with passing function arguments in a list. The following simple example works fine:

logf <- function(par, arguments) {
  mu <- arguments$mean
  sigma <- arguments$sd
  log <- arguments$log
  val <- stats::dnorm(par, mean = mu, sd = sigma, log = log)
  return(val)
}

args <- list(mean = 10, sd = 2, log = TRUE)
x <- ru(logf = logf, arguments = args, d = 1, n = 1000, init = 0.1)
plot(x)

I think that this issue is that `lpost_elfie` has arguments `time`, `time2` etc but no argument called `arguments`. If you want to pass the arguments as a list, which I agree is a convenient thing to do, then the function supplied as the argument `logf` to `rust::ru` needs to have as an argument a list called `arguments` from which you unpack the individual arguments used inside the function. Perhaps you could create a wrapper to `lpost_elfie` that does this.

**Comment by lbelzile** [comment]
Indeed, the newest version has additional arguments that allow users to pass everything at once in a list (akin to `data`, but without formula and without having necessarily arguments of the same length). I modified the reprex above, maybe it's do to repeated calls.

If there is a named list `arguments`, then the function it is called from is called within again with

```
# ...
# extract from `lpost_elife`
# if(!is.null(arguments)){
#    call <- match.call(expand.dots = FALSE)
 #   arguments <- check_arguments(func = lpost_elife, call = call, arguments = arguments)
#    return(do.call(lpost_elife, args = arguments))
#  }
```
where `check_arguments` is defined as
```
check_arguments <- function(func,
                            call,
                            arguments = NULL){
  if(!is.null(arguments)){
    stopifnot("\"arguments\" should be a named list" = is.list(arguments))
  }
  arguments.default <- formals(func)
  new.arguments <- arguments.default
  # Override any default argument with the values in arguments
  new.arguments[names(arguments)] <- arguments
  # Function from https://stackoverflow.com/a/51389399
  to_list <- function(x) {
    xex <- parse(text = x )[[1]]
    xex[[1]] <- quote(list)
    eval.parent(xex)
  }
  supplied.arguments <- to_list(deparse(call[names(call) != "arguments"]))
  new.arguments[names(supplied.arguments)] <- supplied.arguments
  stopifnot("Mandatory \"time\" vector not supplied." = !is.null(new.arguments$time))
  new.arguments$arguments <- NULL
  return(new.arguments)
}
```

**Comment by paulnorthrop** [comment]
Yes, it looks like you are calling `lpost_elife` from within `lpost_elife`, which must be a bad idea.

**Comment by lbelzile** [comment]
Then possibly it's a problem to do with recursive calls. It's probably niche enough that it is not worth fixing and I have a backup option, so I will close the issue. Thanks for your valuable insight.
